apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bap-be-bot-master

resources:
  - ../../base
  - namespace.yaml

secretGenerator:
  - name: secrets
    envs:
      - .env
    type: Opaque

images:
  - name: bap-be-bot
