apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bap-be-bot

resources:
  - secret.yaml
  - deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app: bap-be-bot
      app.kubernetes.io/name: bap-be-bot
      app.kubernetes.io/part-of: bap-be-bot
