apiVersion: v1
kind: Secret
metadata:
  name: bap-be-bot-secrets
type: Opaque
stringData:
  GOOGLE_API_KEY: $(GOOGLE_API_KEY)
  TELEGRAM_BOT_TOKEN: $(TELEGRAM_BOT_TOKEN)
  DISCORD_BOT_TOKEN: $(DISCORD_BOT_TOKEN)

