apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bap-be-bot-dev

resources:
  - ../../base
  - namespace.yaml

secretGenerator:
  - name: bap-be-bot-secrets
    envs:
      - .env
    type: Opaque

images:
  - name: asia-docker.pkg.dev/hieumdd/docker-1/bap-be-bot
    newTag: dev
